### ISSUE TITLE
error with worldguard.

### ISSUE THREAD

**Issue by frogglen** [dolosarafat/AfkPool#1]
```
[03:16:52 ERROR]: Could not pass event PlayerMoveEvent to AfkPool v1.3.1
java.lang.NullPointerException: Cannot invoke "com.sk89q.worldguard.protection.managers.RegionManager.getApplicableRegions(com.sk89q.worldedit.math.BlockVector3)" because "regionManager" is null
        at com.abdullaharafat.AfkPool.App.onPlayerMove(App.java:568) ~[afkpool-1.3.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1540.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:59) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:616) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1735) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:88) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:50) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:186) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1326) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1319) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1296) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1185) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by frogglen** [comment]
```
[00:11:01 WARN]: [AfkPool] Task #34706 for AfkPool v1.3.1 generated an exception
java.lang.NullPointerException: Cannot invoke "com.sk89q.worldguard.protection.managers.RegionManager.getApplicableRegions(com.sk89q.worldedit.math.BlockVector3)" because "regionManager" is null
        at com.abdullaharafat.AfkPool.App$1.run(App.java:89) ~[afkpool-1.3.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:91) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:479) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1477) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:494) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1402) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```
